name = "Figgy"
uuid = "937e9308-674a-48ca-a404-047094c8c902"
authors = ["quinnj <quinn.jacobd@gmail.com>"]
version = "1.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
